

db.proveedores.insertMany([
  { codigo_proveedor: "PROV-001", nombre: "Samsung Electronics America", pais_origen: "Corea del Sur", tipo_producto: "Electronica", contacto: { nombre: "James Kim", email: "jkim@samsung.com", telefono: "+1-800-726-7864" }, condiciones_pago: "30 dias", tiempo_entrega_dias: 15, calificacion: 5, activo: true },
  { codigo_proveedor: "PROV-002", nombre: "HP Inc.", pais_origen: "Estados Unidos", tipo_producto: "Electronica", contacto: { nombre: "Sarah Johnson", email: "sjohnson@hp.com", telefono: "+1-800-474-6836" }, condiciones_pago: "45 dias", tiempo_entrega_dias: 10, calificacion: 5, activo: true },
  { codigo_proveedor: "PROV-003", nombre: "Apple Inc.", pais_origen: "Estados Unidos", tipo_producto: "Electronica", contacto: { nombre: "Michael Chen", email: "mchen@apple.com", telefono: "+1-800-275-2273" }, condiciones_pago: "15 dias", tiempo_entrega_dias: 7, calificacion: 5, activo: true },
  { codigo_proveedor: "PROV-004", nombre: "Sony Corporation", pais_origen: "Japon", tipo_producto: "Electronica", contacto: { nombre: "Hiroshi Tanaka", email: "htanaka@sony.com", telefono: "+1-800-222-7669" }, condiciones_pago: "30 dias", tiempo_entrega_dias: 20, calificacion: 4, activo: true },
  { codigo_proveedor: "PROV-005", nombre: "Chobani LLC", pais_origen: "Estados Unidos", tipo_producto: "Alimentos", contacto: { nombre: "Emily Davis", email: "edavis@chobani.com", telefono: "+1-877-847-6181" }, condiciones_pago: "7 dias", tiempo_entrega_dias: 3, calificacion: 5, activo: true },
  { codigo_proveedor: "PROV-006", nombre: "General Mills Inc.", pais_origen: "Estados Unidos", tipo_producto: "Alimentos", contacto: { nombre: "Robert Wilson", email: "rwilson@generalmills.com", telefono: "+1-800-248-7310" }, condiciones_pago: "15 dias", tiempo_entrega_dias: 5, calificacion: 4, activo: true },
  { codigo_proveedor: "PROV-007", nombre: "PepsiCo", pais_origen: "Estados Unidos", tipo_producto: "Alimentos", contacto: { nombre: "Lisa Anderson", email: "landerson@pepsico.com", telefono: "+1-914-253-2000" }, condiciones_pago: "15 dias", tiempo_entrega_dias: 4, calificacion: 5, activo: true },
  { codigo_proveedor: "PROV-008", nombre: "Fruit of the Loom Inc.", pais_origen: "Estados Unidos", tipo_producto: "Ropa", contacto: { nombre: "David Martinez", email: "dmartinez@fotl.com", telefono: "+1-270-781-6400" }, condiciones_pago: "30 dias", tiempo_entrega_dias: 8, calificacion: 4, activo: true },
  { codigo_proveedor: "PROV-009", nombre: "Mattel Inc.", pais_origen: "Estados Unidos", tipo_producto: "Juguetes", contacto: { nombre: "Jennifer Brown", email: "jbrown@mattel.com", telefono: "+1-800-524-8697" }, condiciones_pago: "30 dias", tiempo_entrega_dias: 12, calificacion: 5, activo: true },
  { codigo_proveedor: "PROV-010", nombre: "Bissell Inc.", pais_origen: "Estados Unidos", tipo_producto: "Hogar", contacto: { nombre: "Thomas Garcia", email: "tgarcia@bissell.com", telefono: "+1-800-237-7691" }, condiciones_pago: "30 dias", tiempo_entrega_dias: 10, calificacion: 4, activo: true },
  { codigo_proveedor: "PROV-011", nombre: "Johnson & Johnson", pais_origen: "Estados Unidos", tipo_producto: "Farmacia", contacto: { nombre: "Amanda White", email: "awhite@jnj.com", telefono: "+1-800-526-3967" }, condiciones_pago: "45 dias", tiempo_entrega_dias: 6, calificacion: 5, activo: true },
  { codigo_proveedor: "PROV-012", nombre: "LEGO Group", pais_origen: "Dinamarca", tipo_producto: "Juguetes", contacto: { nombre: "Anders Nielsen", email: "anielsen@lego.com", telefono: "+45-79-50-60-70" }, condiciones_pago: "30 dias", tiempo_entrega_dias: 18, calificacion: 5, activo: true },
  { codigo_proveedor: "PROV-013", nombre: "Nautilus Inc.", pais_origen: "Estados Unidos", tipo_producto: "Deportes", contacto: { nombre: "Chris Taylor", email: "ctaylor@nautilusinc.com", telefono: "+1-800-628-8458" }, condiciones_pago: "30 dias", tiempo_entrega_dias: 14, calificacion: 4, activo: true },
  { codigo_proveedor: "PROV-014", nombre: "Walmart Private Label", pais_origen: "El Salvador", tipo_producto: "Varios", contacto: { nombre: "Carlos Mejia", email: "cmejia@walmart.com.sv", telefono: "2200-0001" }, condiciones_pago: "Interno", tiempo_entrega_dias: 2, calificacion: 5, activo: true },
  { codigo_proveedor: "PROV-015", nombre: "Hasbro Inc.", pais_origen: "Estados Unidos", tipo_producto: "Juguetes", contacto: { nombre: "Patricia Moore", email: "pmoore@hasbro.com", telefono: "+1-800-255-5516" }, condiciones_pago: "30 dias", tiempo_entrega_dias: 12, calificacion: 4, activo: true }
])